/* This file is part of the libopencm3 project.
 *
 * It was generated by the irq2nvic_h script.
 *
 * These definitions bend every interrupt handler that is defined CMSIS style
 * to the weak symbol exported by libopencm3.
 */

#define GPIO0_IRQHandler gpio0_isr
#define GPIO1_IRQHandler gpio1_isr
#define GPIO2_IRQHandler gpio2_isr
#define GPIO3_IRQHandler gpio3_isr
#define GPIO4_IRQHandler gpio4_isr
#define LPCOMP_IRQHandler lpcomp_isr
#define WDT_IRQHandler wdt_isr
#define SCB0_IRQHandler scb0_isr
#define SCB1_IRQHandler scb1_isr
#define SPCIF_IRQHandler spcif_isr
